# This file was generated by GoReleaser. DO NOT EDIT.
cask "oriel" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "86ea0a2727006dc515276dff7d77f366ae66502df79c0d80b3d646ac68c445ae"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-darwin-amd64"
      binary "oriel-darwin-amd64", target: "oriel"
    end
    on_arm do
      sha256 "7ec54dab05f50a615976487acafdaccd82d12694ea30d78af06ec9bf32019cfc"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-darwin-arm64"
      binary "oriel-darwin-arm64", target: "oriel"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd3ab8adb107458d00947ab6cbe5d219ceee40dc40196dce8a2a3038f8dce1ca"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-linux-amd64"
      binary "oriel-linux-amd64", target: "oriel"
    end
    on_arm do
      sha256 "423fcaf8e135623362e9622209a5f8e285722c25b639374f069de848d1010fb2"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-linux-arm64"
      binary "oriel-linux-arm64", target: "oriel"
    end
  end

  name "oriel"
  desc "Fast, local, single-binary web GUI for Colima & Docker"
  homepage "https://github.com/ParadoxInfinite/oriel"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
