# This file was generated by GoReleaser. DO NOT EDIT.
cask "oriel" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "45a09809f7f7add3cde877cff65f892f37328f1323d0fe4364f8142fa74d351e"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-darwin-amd64"
      binary "oriel-darwin-amd64", target: "oriel"
    end
    on_arm do
      sha256 "0c72a516e04c8240c76b5d9f77f1f66801089f78ee60bc6ec416c5a828a8e51d"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-darwin-arm64"
      binary "oriel-darwin-arm64", target: "oriel"
    end
  end

  on_linux do
    on_intel do
      sha256 "62c04a584b441afcad3dbee7895e08a4fdee132a00d1bb1c5fe019a3db500f06"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-linux-amd64"
      binary "oriel-linux-amd64", target: "oriel"
    end
    on_arm do
      sha256 "2f9ef90529d9789ff891724e23114e32e3ccc005e3e7c644fee3bec27ce73800"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-linux-arm64"
      binary "oriel-linux-arm64", target: "oriel"
    end
  end

  name "oriel"
  desc "Fast, local, single-binary web GUI for Colima & Docker"
  homepage "https://github.com/ParadoxInfinite/oriel"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
