# This file was generated by GoReleaser. DO NOT EDIT.
cask "oriel" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "9a72531481ba1fceefd501b6772535ab25e755b0c40dc2efc1d1bbb2a538e48e"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-darwin-amd64"
      binary "oriel-darwin-amd64", target: "oriel"
    end
    on_arm do
      sha256 "38a9393114db32f8adf18b240d453a121f963aa9b700ad0b192d88114e2fa4af"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-darwin-arm64"
      binary "oriel-darwin-arm64", target: "oriel"
    end
  end

  on_linux do
    on_intel do
      sha256 "efb897ab5104c48da5adb88f3c0d3f05411befea78f63c28325e26cbd6891bbd"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-linux-amd64"
      binary "oriel-linux-amd64", target: "oriel"
    end
    on_arm do
      sha256 "257dfc7bb7882243a430f9dbb2e9640ea7fc6d82a9fb116ab00f69ca5484a972"
      url "https://github.com/ParadoxInfinite/oriel/releases/download/v#{version}/oriel-linux-arm64"
      binary "oriel-linux-arm64", target: "oriel"
    end
  end

  name "oriel"
  desc "Fast, local, single-binary web GUI for Colima & Docker"
  homepage "https://github.com/ParadoxInfinite/oriel"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
